import CameraCore
import CoreGraphics
import Observation

// OWNER: wt/integration. The @Observable surface below is **FROZEN in Phase 0**
// (orchestrator-mediated). UI worktrees bind to these properties and call these
// intents; they do not edit this file. Integration fills the real wiring in
// Phase 2 (currently delegates to an injected `CameraCapturing`).

@MainActor
@Observable
public final class CameraModel {
    // MARK: Exposure
    public var isManualExposure: Bool = false
    public var iso: Float = 100
    public var shutterSeconds: Double = 1.0 / 60.0
    public var exposureLimits: ExposureLimits = .unset

    // MARK: White balance
    public var isManualWhiteBalance: Bool = false
    public var whiteBalanceTemperature: Float = 5000  // Kelvin
    public var whiteBalanceTint: Float = 0
    public var maxWhiteBalanceGain: Float = 4

    // MARK: Focus
    public var isManualFocus: Bool = false
    public var focusLensPosition: Float = 0.5  // 0...1

    // MARK: Capture format
    public var preferProRAW: Bool = true
    public var isProRAWAvailable: Bool = false

    // MARK: Monitoring toggles
    public var zebraEnabled: Bool = false
    public var zebraThreshold: Float = 0.95
    public var focusPeakingEnabled: Bool = false
    public var focusPeakingThreshold: Float = 0.15
    public var histogramEnabled: Bool = true
    public var levelGuideEnabled: Bool = true

    // MARK: Monitoring data
    public var histogram: HistogramData = .empty
    public var rollDegrees: Double = 0
    public var pitchDegrees: Double = 0
    public var isLevel: Bool = false

    // MARK: Status
    public var isSessionRunning: Bool = false
    public var lastCaptureError: String?

    // MARK: Frozen UI ranges (so controls bind without guessing)
    public static let temperatureRange: ClosedRange<Float> = 2500...8000  // Kelvin
    public static let tintRange: ClosedRange<Float> = -150...150
    public static let lensPositionRange: ClosedRange<Float> = 0...1

    // MARK: Dependency
    @ObservationIgnored private let service: any CameraCapturing

    public init(service: any CameraCapturing) {
        self.service = service
        self.exposureLimits = service.exposureLimits
        self.isProRAWAvailable = service.isProRAWAvailable
        wireCallbacks()
    }

    /// Intake for the post-configuration limits and capture results. The service
    /// fires these on a background queue; we hop to the main actor.
    private func wireCallbacks() {
        service.onConfigured = { [weak self] limits, proRAWAvailable in
            Task { @MainActor in
                self?.exposureLimits = limits
                self?.isProRAWAvailable = proRAWAvailable
            }
        }
        service.onCaptureFinished = { [weak self] error in
            Task { @MainActor in
                self?.lastCaptureError = error
            }
        }
    }

    // MARK: Intents (frozen signatures; integration completes the bodies)
    public func startSession() { service.startSession() }
    public func stopSession() { service.stopSession() }
    public func capturePhoto() { service.capturePhoto() }
    public func focusTap(at point: CGPoint) { service.focus(at: point) }

    public func setManualExposure(iso: Float, shutterSeconds: Double) {
        let clampedISO = Exposure.clampISO(iso, into: exposureLimits)
        let clampedShutter = Exposure.clampShutter(shutterSeconds, into: exposureLimits)
        self.iso = clampedISO
        self.shutterSeconds = clampedShutter
        self.isManualExposure = true
        service.setManualExposure(iso: clampedISO, shutterSeconds: clampedShutter)
    }

    public func enableAutoExposure() {
        isManualExposure = false
        service.setAutoExposure()
    }

    public func setWhiteBalance(temperature: Float, tint: Float) {
        whiteBalanceTemperature = temperature
        whiteBalanceTint = tint
        isManualWhiteBalance = true
        let gains = WhiteBalance.gains(temperature: temperature, tint: tint, maxGain: maxWhiteBalanceGain)
        service.setWhiteBalance(gains)
    }

    public func enableAutoWhiteBalance() {
        isManualWhiteBalance = false
        service.setAutoWhiteBalance()
    }

    public func setFocus(lensPosition: Float) {
        focusLensPosition = lensPosition
        isManualFocus = true
        service.setFocus(lensPosition: lensPosition)
    }

    public func enableAutoFocus() {
        isManualFocus = false
        service.setAutoFocus()
    }

    public func setPreferProRAW(_ prefer: Bool) {
        preferProRAW = prefer
        service.setPreferProRAW(prefer)
    }
}
