import CameraCore
import CoreGraphics
import Observation
import simd

// OWNER: wt/integration. The @Observable surface below is **FROZEN in Phase 0**
// (orchestrator-mediated). UI worktrees bind to these properties and call these
// intents; they do not edit this file. Integration fills the real wiring in
// Phase 2 (currently delegates to an injected `CameraCapturing`).

@MainActor
@Observable
public final class CameraModel {
    // MARK: Exposure
    public var isManualExposure: Bool = false
    public var iso: Float = 100
    public var shutterSeconds: Double = 1.0 / 60.0
    public var exposureLimits: ExposureLimits = .unset

    // MARK: White balance
    public var isManualWhiteBalance: Bool = false
    public var whiteBalanceTemperature: Float = 5000  // Kelvin
    public var whiteBalanceTint: Float = 0
    public var maxWhiteBalanceGain: Float = 4

    // MARK: Focus
    public var isManualFocus: Bool = false
    public var focusLensPosition: Float = 0.5  // 0...1

    // MARK: Capture format
    public var preferProRAW: Bool = true
    public var isProRAWAvailable: Bool = false

    // MARK: Monitoring toggles
    public var zebraEnabled: Bool = false
    public var zebraThreshold: Float = 0.95
    public var focusPeakingEnabled: Bool = false
    public var focusPeakingThreshold: Float = 0.15
    public var histogramEnabled: Bool = true
    public var levelGuideEnabled: Bool = true

    // MARK: Monitoring data
    public var histogram: HistogramData = .empty
    public var rollDegrees: Double = 0
    public var pitchDegrees: Double = 0
    public var isLevel: Bool = false

    // MARK: Status
    public var isSessionRunning: Bool = false
    public var lastCaptureError: String?

    // MARK: Frozen UI ranges (so controls bind without guessing)
    public static let temperatureRange: ClosedRange<Float> = 2500...8000  // Kelvin
    public static let tintRange: ClosedRange<Float> = -150...150
    public static let lensPositionRange: ClosedRange<Float> = 0...1

    // MARK: Dependency
    @ObservationIgnored private let service: any CameraCapturing

    // MARK: Integration glue (not part of the frozen @Observable surface)

    /// Owns the frame conduit + histogram/motion producers, and writes the
    /// monitoring-data properties on the main actor (CONTRACTS §6).
    @ObservationIgnored let monitoring = MonitoringHub()

    /// Frame conduit the `CameraMetalView` consumes. Capture feeds it via
    /// `onVideoFrame`; the renderer registers its uploader into it.
    @ObservationIgnored public var framePump: FramePump { monitoring.framePump }
    /// Histogram producer the `CameraMetalView` renderer drives; delivered into
    /// `histogram` on the main actor.
    @ObservationIgnored public var histogramProducer: HistogramProducer { monitoring.histogramProducer }

    /// Derived `PreviewUniforms` snapshot built from the model's monitoring
    /// fields. The FROZEN ABI struct is never mutated structurally — only its
    /// values are populated. `viewSize` is filled by the renderer per drawable.
    @ObservationIgnored public var previewUniforms: PreviewUniforms {
        PreviewUniforms(
            peakingColor: monitoring.peakingColor,
            viewSize: SIMD2<Float>(0, 0),
            zebraThreshold: zebraThreshold,
            peakingThreshold: focusPeakingThreshold,
            rotation: monitoring.rotation,
            zebraEnabled: zebraEnabled ? 1 : 0,
            peakingEnabled: focusPeakingEnabled ? 1 : 0
        )
    }

    public init(service: any CameraCapturing) {
        self.service = service
        self.exposureLimits = service.exposureLimits
        self.isProRAWAvailable = service.isProRAWAvailable
        wireCallbacks()
        monitoring.bind(to: self)
    }

    /// Intake for the post-configuration limits and capture results, plus the
    /// frame conduit. The service fires callbacks on a background queue; observable
    /// writes hop to the main actor. The frame conduit deliberately stays off-main:
    /// `framePump.submit` hands the buffer straight to the renderer's uploader
    /// within the call (the pool recycles it on return — no retain past return).
    private func wireCallbacks() {
        // Frame conduit: a single onVideoFrame fans out to preview upload +
        // histogram (both live inside the Metal renderer's uploader path).
        let pump = monitoring.framePump
        service.onVideoFrame = { pixelBuffer in
            pump.submit(pixelBuffer)
        }
        service.onConfigured = { [weak self] limits, proRAWAvailable in
            Task { @MainActor in
                self?.exposureLimits = limits
                self?.isProRAWAvailable = proRAWAvailable
            }
        }
        service.onCaptureFinished = { [weak self] error in
            Task { @MainActor in
                self?.lastCaptureError = error
            }
        }
    }

    // MARK: Intents (frozen signatures; integration completes the bodies)
    public func startSession() {
        service.startSession()
        monitoring.startMotion()
        isSessionRunning = true
    }

    public func stopSession() {
        service.stopSession()
        monitoring.stopMotion()
        isSessionRunning = false
    }
    public func capturePhoto() { service.capturePhoto() }
    public func focusTap(at point: CGPoint) { service.focus(at: point) }

    public func setManualExposure(iso: Float, shutterSeconds: Double) {
        let clampedISO = Exposure.clampISO(iso, into: exposureLimits)
        let clampedShutter = Exposure.clampShutter(shutterSeconds, into: exposureLimits)
        self.iso = clampedISO
        self.shutterSeconds = clampedShutter
        self.isManualExposure = true
        service.setManualExposure(iso: clampedISO, shutterSeconds: clampedShutter)
    }

    public func enableAutoExposure() {
        isManualExposure = false
        service.setAutoExposure()
    }

    public func setWhiteBalance(temperature: Float, tint: Float) {
        whiteBalanceTemperature = temperature
        whiteBalanceTint = tint
        isManualWhiteBalance = true
        let gains = WhiteBalance.gains(temperature: temperature, tint: tint, maxGain: maxWhiteBalanceGain)
        service.setWhiteBalance(gains)
    }

    public func enableAutoWhiteBalance() {
        isManualWhiteBalance = false
        service.setAutoWhiteBalance()
    }

    public func setFocus(lensPosition: Float) {
        focusLensPosition = lensPosition
        isManualFocus = true
        service.setFocus(lensPosition: lensPosition)
    }

    public func enableAutoFocus() {
        isManualFocus = false
        service.setAutoFocus()
    }

    public func setPreferProRAW(_ prefer: Bool) {
        preferProRAW = prefer
        service.setPreferProRAW(prefer)
    }
}
