import CameraCore
import CoreGraphics
import Observation
import simd

// OWNER: wt/integration. The @Observable surface below is **FROZEN in Phase 0**
// (orchestrator-mediated). UI worktrees bind to these properties and call these
// intents; they do not edit this file. Integration fills the real wiring in
// Phase 2 (currently delegates to an injected `CameraCapturing`).

@MainActor
@Observable
public final class CameraModel {
    // MARK: Exposure
    public var isManualExposure: Bool = false
    public var iso: Float = 100
    public var shutterSeconds: Double = 1.0 / 60.0
    public var exposureLimits: ExposureLimits = .unset

    // MARK: White balance
    public var isManualWhiteBalance: Bool = false
    public var whiteBalanceTemperature: Float = 5000  // Kelvin
    public var whiteBalanceTint: Float = 0
    public var maxWhiteBalanceGain: Float = 4

    // MARK: Focus
    public var isManualFocus: Bool = false
    public var focusLensPosition: Float = 0.5  // 0...1

    // MARK: Capture format
    public var preferProRAW: Bool = true
    public var isProRAWAvailable: Bool = false

    // MARK: Preview framing (composition guide; RAW still captures full sensor)
    var aspectRatio: CameraAspectRatio = .fourThree

    // MARK: Zoom
    public var zoomFactor: CGFloat = 1.0
    public var minZoom: CGFloat = 1.0
    public var maxZoom: CGFloat = 10.0
    /// Show the vertical zoom slider overlay (settings-configurable).
    var showZoomSlider: Bool = false
    /// Whether the settings drawer is expanded (UI state shared so overlays can
    /// make room for each other).
    var showSettings: Bool = false

    // MARK: Advanced capture options (amendment A3)
    public var highRes48MP: Bool = false
    public var rawBracketing: Bool = false
    public var hdr10Bit: Bool = false
    public var maxQuality: Bool = true
    public var is48MPAvailable: Bool = false
    public var isRAWBracketingAvailable: Bool = false
    public var is10BitHDRAvailable: Bool = false

    // MARK: Monitoring toggles
    public var zebraEnabled: Bool = false
    public var zebraThreshold: Float = 0.95
    public var focusPeakingEnabled: Bool = false
    public var focusPeakingThreshold: Float = 0.15
    public var histogramEnabled: Bool = false
    public var levelGuideEnabled: Bool = true

    // MARK: Monitoring data
    public var histogram: HistogramData = .empty
    public var rollDegrees: Double = 0
    public var pitchDegrees: Double = 0
    public var isLevel: Bool = false

    // MARK: Status
    public var isSessionRunning: Bool = false
    public var lastCaptureError: String?
    /// Monotonic counter bumped the instant a capture is *initiated* (the shutter
    /// is pressed). The UI observes the change to fire the immediate capture
    /// feedback — a haptic tap + shutter blink — before the photo is processed.
    public private(set) var captureStartCount: Int = 0
    /// Monotonic counter bumped each time a capture is actually *saved* (a DNG
    /// reached disk). Paired with `lastCaptureThumbnail`; the UI flashes the
    /// thumbnail briefly when this changes.
    public private(set) var captureSavedCount: Int = 0
    /// Upright preview of the most recently saved capture, for the confirmation
    /// thumbnail. `nil` until the first successful save.
    public private(set) var lastCaptureThumbnail: CGImage?

    // MARK: Frozen UI ranges (so controls bind without guessing)
    public static let temperatureRange: ClosedRange<Float> = 2500...8000  // Kelvin
    public static let tintRange: ClosedRange<Float> = -150...150
    public static let lensPositionRange: ClosedRange<Float> = 0...1

    // MARK: Dependency
    @ObservationIgnored private let service: any CameraCapturing

    // MARK: Integration glue (not part of the frozen @Observable surface)

    /// Owns the frame conduit + histogram/motion producers, and writes the
    /// monitoring-data properties on the main actor (CONTRACTS §6).
    @ObservationIgnored let monitoring = MonitoringHub()

    /// Frame conduit the `CameraMetalView` consumes. Capture feeds it via
    /// `onVideoFrame`; the renderer registers its uploader into it.
    @ObservationIgnored public var framePump: FramePump { monitoring.framePump }
    /// Histogram producer the `CameraMetalView` renderer drives; delivered into
    /// `histogram` on the main actor.
    @ObservationIgnored public var histogramProducer: HistogramProducer { monitoring.histogramProducer }

    /// Derived `PreviewUniforms` snapshot built from the model's monitoring
    /// fields. The FROZEN ABI struct is never mutated structurally — only its
    /// values are populated. `viewSize` is filled by the renderer per drawable.
    @ObservationIgnored public var previewUniforms: PreviewUniforms {
        PreviewUniforms(
            peakingColor: monitoring.peakingColor,
            viewSize: SIMD2<Float>(0, 0),
            zebraThreshold: zebraThreshold,
            peakingThreshold: focusPeakingThreshold,
            rotation: monitoring.rotation,
            zebraEnabled: zebraEnabled ? 1 : 0,
            peakingEnabled: focusPeakingEnabled ? 1 : 0
        )
    }

    public init(service: any CameraCapturing) {
        self.service = service
        self.exposureLimits = service.exposureLimits
        self.isProRAWAvailable = service.isProRAWAvailable
        wireCallbacks()
        monitoring.bind(to: self)
    }

    /// Intake for the post-configuration limits and capture results, plus the
    /// frame conduit. The service fires callbacks on a background queue; observable
    /// writes hop to the main actor. The frame conduit deliberately stays off-main:
    /// `framePump.submit` hands the buffer straight to the renderer's uploader
    /// within the call (the pool recycles it on return — no retain past return).
    private func wireCallbacks() {
        // Frame conduit: a single onVideoFrame fans out to preview upload +
        // histogram (both live inside the Metal renderer's uploader path).
        let pump = monitoring.framePump
        service.onVideoFrame = { pixelBuffer in
            pump.submit(pixelBuffer)
        }
        service.onConfigured = { [weak self] limits, proRAWAvailable in
            Task { @MainActor in
                self?.exposureLimits = limits
                self?.isProRAWAvailable = proRAWAvailable
            }
        }
        service.onCaptureFinished = { [weak self] error in
            Task { @MainActor in
                self?.lastCaptureError = error
            }
        }
        service.onCaptureThumbnail = { [weak self] image in
            Task { @MainActor in
                guard let self else { return }
                // A thumbnail only arrives on a successful save, so this is the
                // honest "photo landed" moment that drives the confirmation chip.
                self.lastCaptureThumbnail = image
                self.captureSavedCount += 1
            }
        }
        service.onZoomRange = { [weak self] lo, hi in
            Task { @MainActor in
                self?.minZoom = lo
                self?.maxZoom = max(lo, hi)
            }
        }
        service.onCaptureCapabilities = { [weak self] caps in
            Task { @MainActor in
                guard let self else { return }
                self.is48MPAvailable = caps.supports48MP
                self.isRAWBracketingAvailable = caps.supportsRAWBracketing
                self.is10BitHDRAvailable = caps.supports10BitHDR
            }
        }
        wireDeviceValues()
    }

    /// Live device values for read-only readouts. Only adopt them for axes
    /// currently in auto — manual axes keep the user's chosen values.
    private func wireDeviceValues() {
        service.onDeviceValues = { [weak self] values in
            Task { @MainActor in
                guard let self else { return }
                if !self.isManualExposure {
                    self.iso = values.iso
                    self.shutterSeconds = values.shutterSeconds
                }
                if !self.isManualWhiteBalance {
                    self.whiteBalanceTemperature = values.whiteBalanceTemperature
                    self.whiteBalanceTint = values.whiteBalanceTint
                }
                if !self.isManualFocus {
                    self.focusLensPosition = values.lensPosition
                }
            }
        }
    }

    // MARK: Intents (frozen signatures; integration completes the bodies)
    public func startSession() {
        service.startSession()
        monitoring.startMotion()
        isSessionRunning = true
    }

    public func stopSession() {
        service.stopSession()
        monitoring.stopMotion()
        isSessionRunning = false
    }
    public func capturePhoto() {
        // Bump first so the UI fires immediate feedback the instant the shutter
        // is pressed, independent of how long the capture+save takes.
        captureStartCount &+= 1
        service.capturePhoto()
    }
    public func focusTap(at point: CGPoint) { service.focus(at: point) }

    public func setManualExposure(iso: Float, shutterSeconds: Double) {
        let clampedISO = Exposure.clampISO(iso, into: exposureLimits)
        let clampedShutter = Exposure.clampShutter(shutterSeconds, into: exposureLimits)
        self.iso = clampedISO
        self.shutterSeconds = clampedShutter
        self.isManualExposure = true
        service.setManualExposure(iso: clampedISO, shutterSeconds: clampedShutter)
    }

    public func enableAutoExposure() {
        isManualExposure = false
        service.setAutoExposure()
    }

    public func setWhiteBalance(temperature: Float, tint: Float) {
        whiteBalanceTemperature = temperature
        whiteBalanceTint = tint
        isManualWhiteBalance = true
        let gains = WhiteBalance.gains(temperature: temperature, tint: tint, maxGain: maxWhiteBalanceGain)
        service.setWhiteBalance(gains)
    }

    public func enableAutoWhiteBalance() {
        isManualWhiteBalance = false
        service.setAutoWhiteBalance()
    }

    public func setFocus(lensPosition: Float) {
        focusLensPosition = lensPosition
        isManualFocus = true
        service.setFocus(lensPosition: lensPosition)
    }

    public func enableAutoFocus() {
        isManualFocus = false
        service.setAutoFocus()
    }

    public func setPreferProRAW(_ prefer: Bool) {
        preferProRAW = prefer
        service.setPreferProRAW(prefer)
    }

    public func setZoom(_ factor: CGFloat) {
        let clamped = min(max(factor, minZoom), maxZoom)
        zoomFactor = clamped
        service.setZoom(factor: clamped)
    }

    /// Push the current advanced capture options to the service. Called by the
    /// settings toggles after they update their backing property.
    public func pushCaptureOptions() {
        service.setCaptureOptions(
            CaptureOptions(
                highResolution: highRes48MP,
                rawBracketing: rawBracketing,
                hdr10BitColor: hdr10Bit,
                maxQuality: maxQuality
            )
        )
    }
}
